from method_lib import dataImporter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as spi


'''
This tech-demo will go through the programs features so far. The main process is stored in the method_lib folder. The dataImporter.py file includes several data related functions, as well as the data classes.

Each dataclass contains an ID and a data frame. When the object is created, it can then be stored by a serilization process.

If desired, the source data can be generated by a method in the sourceData object.

This simple demo will load one filter and generate a simple BB spectrum from 0.2 µm to 13 µm at 5000 K and save it to a .csv file for repeated use.

the filter can be chosen by the user. For testing, a Thorlabs filter FB1750-500 was used. with its corresponding .xlsx file. This datafile can be found in test_data.

Developer note:

As of now, there is no nice way to easily match the spectrum ranges of efficiency data and some arbetrary wavelength range. For the next version, there will be a common limit found based on the available data. Or there will be a mothod for efficiency estimation. that is TBD.
'''

# Efficiency data FB1750-500
filterTLabs = dataImporter.efficiencyData(
    'test_data/FB1750-500.xlsx', 'filter', 'FB1750-500')

print(filterTLabs.df.head())

dataImporter.storeEfficiencyData(filterTLabs)

'''
Data can be loaded again using:
filterTLabs = dataImporter.loadStoredObject(dataCache/FB1750-500.pickle)

Works for any of the pickle files.
'''

# Source generation
BlackBody = dataImporter.sourceData('BB_5000K')
temperature = 5000  # K
lambda_ = filterTLabs.df['Wavelength (nm)']  # nm
# If user specified use -> lambda_ = np.arange(0.4e-6, 13e-6, 10e-9)

lambda_ *= 1e-3  # Spectrum in µm
BlackBody.generateSourceData_BB(
    lambda_, temperature, showNPHOTONS=True, unitsSI=True)

print('\n First couple of rows for the BB data frame:\n', BlackBody.df.head())
print('\n The units of the BB data:\n', BlackBody.units)
dataImporter.storeSourceData(BlackBody, generateDataFile=True)

fig, (ax1, ax2) = plt.subplots(2, 1)

ax1.plot(lambda_, BlackBody.df[BlackBody.sourceID], 'k')
ax1.set_ylabel(f"$[{BlackBody.units}]$")

ax2.plot(lambda_, filterTLabs.df['% Transmission'], 'k')
ax2.set_ylabel('Transmission %')
ax2.set_xlabel('Wavelengt [µm]')
plt.show()

resultingData = pd.DataFrame()
resultingData["Wavelength (µm)"] = lambda_
resultingData["Tranfered Source"] = filterTLabs.df["% Transmission"] / \
    100 * BlackBody.df[BlackBody.sourceID]

plt.plot(lambda_, resultingData["Tranfered Source"], 'k')
plt.plot(lambda_, BlackBody.df[BlackBody.sourceID], '--k')
plt.xlabel('Wavelengt [µm]')
plt.ylabel(f"$[{BlackBody.units}]$")
plt.show()

print("\nFirst few rows of the resultingData dataframe:\n", resultingData)

originalSourceIntegration = spi.integrate.trapezoid(
    BlackBody.df[BlackBody.sourceID], lambda_)  # photons/m^2/s

print("Original spectral integral:", originalSourceIntegration, f"photons/m^2/s")

spectralSourceIntegration = spi.integrate.trapezoid(
    resultingData['Tranfered Source'], lambda_)  # photons/m^2/s

print("Spectral integral:", spectralSourceIntegration, f"photons/m^2/s")
